spring.application.name=taskapi
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Activate H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Now you can access the database directly at
# http://localhost:8080/h2-console
# Login credentials:
# JDBC URL: jdbc:h2:mem:taskdb
# username: sa
# password: (leave empty)

jwt.secret=deinSuperGeheimesPasswortDasMindestens32ZeichenLangSeinMuss123!
jwt.expiration=86400000

#jwt.secret -> secret Key the server uses to sign and verify JWT Tokens. Only the Server knows it,
#              so others cannot forge valid tokens. In real projects it is never stored in code or Git
#              Simplified here for learning
#jwt.expiration -> How long a token is valid (ms). 86400000 ms = 24h
